#!/bin/bash
echo -------------------------------------------------------------
echo This will work, but you\'d better run ./gradlew clean install
echo -------------------------------------------------------------
#
buildProject() {
  WORK_DIR=$1
  cd $WORK_DIR
  echo Building $WORK_DIR
  ../gradlew clean build install
  cd ..
}
echo Building everything...
buildProject SevenSegDisplay
buildProject I2C
buildProject ADC
buildProject DAC
buildProject GPIO.01
# buildProject GPS.sun.servo
buildProject PhoneKeyboard3x4
buildProject Arduino.RaspberryPI
buildProject RangeSensor
buildProject PIR
buildProject FONA
buildProject Relay
buildProject WeatherStation
buildProject RasPiSamples
buildProject LelandOilDetector
echo Done!
