#!/bin/bash
echo This will work, but you\'d better run ./gradlew clean install
#
buildProject() {
  WORK_DIR=$1
  cd $WORK_DIR
  echo Building $WORK_DIR
  ../gradlew clean build install
  cd ..
}
echo Building everything...
buildProject SevenSegDisplay
buildProject AdafruitI2C
buildProject ADC
buildProject DAC
buildProject GPIO.01
# buildProject GPS.sun.servo
buildProject PhoneKeyboard3x4
buildProject Arduino.RaspberryPI
buildProject RangeSensor
buildProject PIR
buildProject Relay
buildProject WeatherStation
buildProject RasPiSamples
echo Done!
