#!/bin/bash
PI4J_HOME=/opt/pi4j
CP=./classes
CP=$CP:../ADC/classes
CP=$CP:$PI4J_HOME/lib/pi4j-core.jar
#
JAVA_OPTIONS=
# JAVA_OPTIONS="$JAVA_OPTIONS -Dverbose=true"
# JAVA_OPTIONS="$JAVA_OPTIONS -client -agentlib:jdwp=transport=dt_socket,server=y,address=4000" 
echo Running...
sudo java $JAVA_OPTIONS -cp $CP breadboard.game.ReflexGame

